# NOTE: This docker container is built automatically
#       from Travis-CI after passing unit tests

FROM python:alpine

COPY . /code
WORKDIR /code

RUN apk add --no-cache --virtual .build-deps gcc g++
RUN pip3 install --upgrade pip
RUN pip3 install --requirement requirements.txt

ENV WORKER_NAME="worker-1"
ENV WITH_SCHEDULER=""

CMD rq worker --config rq_settings --name $WORKER_NAME $WITH_SCHEDULER

# Define environment variables
# NOTE: The following environment variables are expected to be set for testing:
#   DB_ENDPOINT
#	TX_DATABASE_PW
#	AWS_ACCESS_KEY_ID
#	AWS_SECRET_ACCESS_KEY
# NOTE: The following environment variables are optional:
#	REDIS_URL (can be omitted for testing to use a local instance)
#	DEBUG_MODE (can be set to any non-blank string to run in debug mode for testing)
#	GRAPHITE_HOSTNAME (defaults to localhost if missing)
#	QUEUE_PREFIX (defaults to '', set to dev- for testing)


# NOTE: To build use:
#           docker build --file Dockerfile-developBranch --tag unfoldingword/door43_job_handler:develop .


#       To test (assuming that the confidential environment variables are already set in the current environment) use:
#           docker run --env DB_ENDPOINT --env TX_DATABASE_PW --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env QUEUE_PREFIX=dev- --env DEBUG_MODE=True --net="host" --name door43_job_handler --rm door43_job_handler:develop


#       To run in production use with the desired values:
#           docker run --env DB_ENDPOINT --env TX_DATABASE_PW=<tx_db_pw> --env AWS_ACCESS_KEY_ID=<access_key> --env AWS_SECRET_ACCESS_KEY=<sa_key> --env GRAPHITE_HOSTNAME=<graphite_hostname> --env REDIS_URL=<redis_url> --net="host" --name door43_job_handler --detach --rm door43_job_handler:develop
